services:
  - type: web
    name: tracedhealth
    env: python
    buildCommand: "git lfs pull && pip install -r requirements.txt"
    startCommand: "gunicorn traced_app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
