import sqlite3, uuid, json, re

DB = '/Users/evan/Desktop/Traceddatabase/traced.db'
conn = sqlite3.connect(DB)
c = conn.cursor()
conn.execute("PRAGMA journal_mode=WAL")

def get_company_id(name_like):
    row = c.execute("SELECT id FROM companies WHERE name LIKE ?", (f'%{name_like}%',)).fetchone()
    return row[0] if row else None

def make_slug(name):
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')

brands = [
  {"name":"Quest Nutrition","category":"Supplements","sub_category":"Protein Bars","parent_like":"Simply Good","acquired_year":2019,"founded_year":2010,"pe_owned":0,"contradiction_score":58,"founder_names":"Tom Bilyeu, Ron Penna, Shannon Penna","origin_story":"Founded in 2010 in Los Angeles, Quest became one of the fastest-growing food companies in history by pioneering high-protein, low-sugar snack bars.","headline_finding":"Acquired by Simply Good Foods in 2019 for $1B; parent company also owns Atkins diet products.","marketing_claims":"High protein, low sugar, no compromise","certifications":"","share_text":"Quest Nutrition was acquired by Simply Good Foods (the Atkins company) in 2019 for $1B. Check it on Traced.","contradiction_reasons":json.dumps(["Acquired by public holding company 2019","Parent also owns Atkins brand - competing diet philosophies","Original founders departed post-acquisition"])},
  {"name":"Orgain","category":"Supplements","sub_category":"Protein Shakes","parent_like":"Nestle","acquired_year":2022,"founded_year":2009,"pe_owned":0,"contradiction_score":52,"founder_names":"Andrew Abraham","origin_story":"Founded by Dr. Andrew Abraham, a cancer survivor who created clean protein shakes after being dissatisfied with existing options during his recovery.","headline_finding":"Nestlé acquired majority stake in Orgain in 2022, bringing the clean-label brand under one of the world's largest food conglomerates.","marketing_claims":"Clean, organic, doctor-developed","certifications":"USDA Organic, Non-GMO Project Verified","share_text":"Orgain was acquired by Nestlé in 2022. The clean-protein brand is now part of the world's largest food company. Check it on Traced.","contradiction_reasons":json.dumps(["Nestlé acquisition 2022","Nestlé has faced decades of infant formula marketing controversies","Clean branding under conglomerate ownership"])},
  {"name":"Muscle Milk","category":"Supplements","sub_category":"Protein Shakes","parent_like":"Hormel","acquired_year":2014,"founded_year":1998,"pe_owned":0,"contradiction_score":72,"founder_names":"Greg Pickett","origin_story":"Created by CytoSport in 1998, Muscle Milk pioneered mainstream protein shakes before being acquired by Hormel in 2014.","headline_finding":"Owned by Hormel Foods (SPAM, Skippy) since 2014. Hormel has faced multiple FTC actions and is one of the largest conventional meat processors in the US.","marketing_claims":"Great taste, real results","certifications":"","share_text":"Muscle Milk is owned by Hormel Foods — the company behind SPAM and Skippy. See the full picture on Traced.","contradiction_reasons":json.dumps(["Owned by Hormel (SPAM, Skippy)","Parent has faced FTC false advertising actions","Conventional meat conglomerate ownership","CytoSport FTC settlement re: misleading health claims"])},
  {"name":"Premier Protein","category":"Supplements","sub_category":"Protein Shakes","parent_like":"BellRing","acquired_year":2019,"founded_year":2001,"pe_owned":0,"contradiction_score":48,"founder_names":"Darcy Horn Davenport","origin_story":"Premier Protein was developed as a premium ready-to-drink protein shake, originally under Post Holdings before BellRing Brands was spun off.","headline_finding":"BellRing Brands (NYSE: BRBR) was spun off from Post Holdings in 2019 to hold Premier Protein, Dymatize, and PowerBar.","marketing_claims":"30g protein, 1g sugar","certifications":"","share_text":"Premier Protein is owned by BellRing Brands, a publicly traded holding company spun off from Post Holdings in 2019. Check it on Traced.","contradiction_reasons":json.dumps(["Public conglomerate ownership via BellRing Brands","Post Holdings parent historically acquired and financialized many food brands","Aggressive growth-at-scale model"])},
  {"name":"Optimum Nutrition","category":"Supplements","sub_category":"Protein Powder","parent_like":"Glanbia","acquired_year":2008,"founded_year":1986,"pe_owned":0,"contradiction_score":45,"founder_names":"Michael Costello","origin_story":"Founded in 1986, ON created Gold Standard 100% Whey, the best-selling protein powder in the world. Acquired by Glanbia Performance Nutrition.","headline_finding":"Glanbia plc (Ireland) acquired Optimum Nutrition in 2008. Glanbia also owns BSN, Think!, Isopure, and Amazing Grass.","marketing_claims":"Gold standard in protein","certifications":"Informed Sport, NSF Certified for Sport","share_text":"Optimum Nutrition (Gold Standard Whey) has been owned by Irish conglomerate Glanbia since 2008. Check it on Traced.","contradiction_reasons":json.dumps(["Glanbia conglomerate ownership since 2008","Parent manages multiple competing protein brands","Scale-driven formulation decisions"])},
  {"name":"Garden of Life","category":"Supplements","sub_category":"Vitamins & Supplements","parent_like":"Nestle","acquired_year":2017,"founded_year":2000,"pe_owned":0,"contradiction_score":65,"founder_names":"Jordan Rubin","origin_story":"Jordan Rubin founded Garden of Life after overcoming Crohn's disease through nutrition. The brand built a following with whole-food based supplements.","headline_finding":"Nestlé Health Science acquired Garden of Life in 2017. The whole-food supplement pioneer is now part of the world's largest food company.","marketing_claims":"Whole food vitamins, live probiotics, certified organic","certifications":"USDA Organic, Non-GMO Project Verified, NSF Certified, Certified B Corp (pre-acquisition)","share_text":"Garden of Life was acquired by Nestlé Health Science in 2017. The whole-food supplement brand now operates under the world's largest food company. Traced it.","contradiction_reasons":json.dumps(["Nestlé acquisition 2017","Lost Certified B Corp status post-acquisition","Nestlé history of aggressive marketing against breastfeeding","Founder Jordan Rubin departed post-acquisition"])},
  {"name":"Vega","category":"Supplements","sub_category":"Plant Protein","parent_like":"Danone","acquired_year":2015,"founded_year":2004,"pe_owned":0,"contradiction_score":55,"founder_names":"Charles Chang, Brendan Brazier","origin_story":"Brendan Brazier, a professional Ironman triathlete, created Vega as a plant-based performance nutrition brand. Acquired by WhiteWave (then Danone).","headline_finding":"Vega was acquired by WhiteWave in 2015, then absorbed into Danone when Danone acquired WhiteWave in 2017 for $12.5B.","marketing_claims":"Plant-powered performance","certifications":"USDA Organic, Non-GMO Project Verified","share_text":"Vega plant protein is ultimately owned by Danone after a 2017 acquisition chain. Check it on Traced.","contradiction_reasons":json.dumps(["Double acquisition: WhiteWave 2015, then Danone 2017","Danone faced shareholder pressure to drop ESG commitments","Original founders departed","Danone faced boycotts over infant formula practices"])},
  {"name":"Vital Proteins","category":"Supplements","sub_category":"Collagen","parent_like":"Nestle","acquired_year":2021,"founded_year":2013,"pe_owned":0,"contradiction_score":60,"founder_names":"Kurt Seidensticker","origin_story":"Kurt Seidensticker founded Vital Proteins in 2013 after personal experience with the benefits of collagen peptides. The brand grew to $100M+ in revenue.","headline_finding":"Nestlé Health Science acquired majority stake in 2021. Jennifer Aniston, the brand's spokesperson, reportedly held equity that was bought out.","marketing_claims":"Daily wellness through collagen","certifications":"NSF Certified, Whole30 Approved","share_text":"Vital Proteins collagen is now majority owned by Nestlé Health Science since 2021. Check it on Traced.","contradiction_reasons":json.dumps(["Nestlé majority acquisition 2021","Nestlé history with infant formula WHO code violations","Collagen sourcing transparency questions post-acquisition"])},
  {"name":"Liquid I.V.","category":"Beverages","sub_category":"Hydration","parent_like":"Unilever","acquired_year":2020,"founded_year":2012,"pe_owned":0,"contradiction_score":62,"founder_names":"Brandin Cohen","origin_story":"Brandin Cohen founded Liquid I.V. in 2012 using Cellular Transport Technology. The brand paired a 1-for-1 donation model with rapid DTC growth.","headline_finding":"Unilever acquired Liquid I.V. in 2020. The donation-driven hydration brand is now part of Unilever's $50B personal care and food conglomerate.","marketing_claims":"Hydrate 2-3x faster than water alone","certifications":"Non-GMO Project Verified","share_text":"Liquid I.V. was acquired by Unilever in 2020. The charity-branded hydration drink is now part of one of the world's largest consumer goods companies. Check it on Traced.","contradiction_reasons":json.dumps(["Unilever acquisition 2020","Unilever has faced scrutiny for greenwashing and sustainability claims","1-for-1 donation program fate unclear post-acquisition","Unilever's Ben & Jerry's CEO fired after Palestinian activism"])},
  {"name":"Poppi","category":"Beverages","sub_category":"Prebiotic Soda","parent_like":"PepsiCo","acquired_year":2025,"founded_year":2018,"pe_owned":0,"contradiction_score":68,"founder_names":"Allison Ellsworth, Stephen Ellsworth","origin_story":"Allison Ellsworth started selling apple cider vinegar drinks at a farmers market in 2018. After appearing on Shark Tank, Poppi grew to $100M+ revenue before PepsiCo acquisition.","headline_finding":"PepsiCo acquired Poppi in 2025 for ~$1.65B. PepsiCo simultaneously sells Gatorade, Mountain Dew, and Pepsi — products with opposite health profiles.","marketing_claims":"Gut health, feel good inside","certifications":"Non-GMO Project Verified","formula_changed_post_acquisition":0,"share_text":"Poppi prebiotic soda was acquired by PepsiCo in 2025 for $1.65B — the same company that makes Mountain Dew and Doritos. Check it on Traced.","contradiction_reasons":json.dumps(["PepsiCo acquisition 2025 for ~$1.65B","Parent simultaneously markets products like Mountain Dew and Gatorade","PepsiCo lobbied against soda taxes and warning labels","Class action lawsuit over prebiotic health claims filed 2024"])},
  {"name":"Olipop","category":"Beverages","sub_category":"Functional Soda","parent_like":None,"acquired_year":None,"founded_year":2018,"pe_owned":0,"contradiction_score":18,"founder_names":"Ben Goodwin, David Lester","origin_story":"Ben Goodwin created Olipop after years formulating fermented wellness beverages. The brand uses a proprietary blend of botanicals and plant fiber to support digestive health.","headline_finding":"Remains independent as of 2025. One of the few fast-growth functional beverage brands not acquired by a major conglomerate.","marketing_claims":"A new kind of soda, supports gut health","certifications":"Non-GMO Project Verified, Low FODMAP Certified","share_text":"Olipop is still independent as of 2025 — rare for a fast-growing functional beverage brand. Check it on Traced.","contradiction_reasons":json.dumps(["Independent brand, no major acquisition","Venture-backed with Mondelez Strategic Ventures as investor (minority stake)","Growing quickly — acquisition risk remains"])},
  {"name":"Celsius","category":"Beverages","sub_category":"Energy Drinks","parent_like":None,"acquired_year":None,"founded_year":2004,"pe_owned":0,"contradiction_score":42,"founder_names":"Steve Haley","origin_story":"Celsius Holdings was founded in 2004 with the premise that its energy drinks accelerate metabolism. It became a Nasdaq-listed company (CELH) and grew massively via PepsiCo distribution deal.","headline_finding":"Celsius is publicly traded (Nasdaq: CELH). PepsiCo invested $550M for an ~8.5% stake in 2022, giving PepsiCo distribution rights and influence without full ownership.","marketing_claims":"Live fit, clinically proven to accelerate metabolism","certifications":"NSF Certified for Sport","share_text":"Celsius energy drinks are publicly traded (Nasdaq: CELH) with PepsiCo as an 8.5% strategic investor since 2022. Check it on Traced.","contradiction_reasons":json.dumps(["PepsiCo $550M strategic investment and distribution deal","FTC investigation into energy drink health claims industry-wide","Class action lawsuit over metabolism acceleration claims","High caffeine content (200mg) marketed as wellness"])},
  {"name":"Happy Baby","category":"Baby Food","sub_category":"Organic Baby Food","parent_like":"Danone","acquired_year":2013,"founded_year":2006,"pe_owned":0,"contradiction_score":58,"founder_names":"Shazi Visram","origin_story":"Shazi Visram founded Happy Baby in 2006 with a mission to make organic baby food accessible. The brand grew rapidly and was acquired by Groupe Danone in 2013.","headline_finding":"Danone acquired Happy Family (Happy Baby parent) in 2013 for ~$361M. The organic baby food brand is now part of the same company as Danimals, Dannon yogurt, and Evian.","marketing_claims":"Organic, non-GMO, nutrient-dense baby food","certifications":"USDA Organic, Non-GMO Project Verified","share_text":"Happy Baby organic baby food is owned by Danone since 2013. The brand that promises pure nutrition is part of a $25B food conglomerate. Check it on Traced.","contradiction_reasons":json.dumps(["Danone acquisition 2013","Danone dropped ESG commitments under shareholder pressure","Congressional report 2021 found heavy metals in organic baby foods","Parent also sells Danimals with high sugar content"])},
  {"name":"Plum Organics","category":"Baby Food","sub_category":"Organic Baby Food","parent_like":"Campbell","acquired_year":2013,"founded_year":2007,"pe_owned":0,"contradiction_score":62,"founder_names":"Gigi Lee Chang, Neil Grimmer","origin_story":"Neil Grimmer co-founded Plum Organics in 2007. The brand pioneered squeezable organic baby food pouches. Campbell Soup acquired it in 2013 for ~$249M.","headline_finding":"Campbell Soup Company owns Plum Organics. The baby food brand sits alongside Goldfish crackers and Campbell's condensed soups in one of America's oldest CPG companies.","marketing_claims":"Organic, real ingredients for real babies","certifications":"USDA Organic, Non-GMO Project Verified","share_text":"Plum Organics baby food is owned by Campbell Soup Company (Goldfish, Pepperidge Farm) since 2013. Check it on Traced.","contradiction_reasons":json.dumps(["Campbell Soup acquisition 2013","Parent sells ultra-processed sodium-heavy products like Campbell soups","Congressional report found heavy metals in baby food pouches 2021","Founder Neil Grimmer departed post-acquisition"])},
  {"name":"Earth's Best","category":"Baby Food","sub_category":"Organic Baby Food","parent_like":"Hain Celestial","acquired_year":1993,"founded_year":1985,"pe_owned":0,"contradiction_score":55,"founder_names":"Ron Koss, Arnie Koss","origin_story":"Brothers Ron and Arnie Koss launched Earth's Best in 1985 as the first certified organic baby food brand in the US. It was acquired by Heinz in 1993, then by Hain Celestial.","headline_finding":"Hain Celestial has owned Earth's Best since 1998. Hain is a publicly traded company that has faced SEC accounting investigations and multiple brand divestitures.","marketing_claims":"America's first organic baby food brand","certifications":"USDA Organic","share_text":"Earth's Best, America's first organic baby food brand, is owned by Hain Celestial — a publicly traded company that has faced SEC scrutiny. Check it on Traced.","contradiction_reasons":json.dumps(["Hain Celestial ownership since 1998","Hain faced SEC accounting investigation 2016-2018","Congressional report 2021 found inorganic arsenic in Earth's Best products","Multiple Hain brand divestitures signal portfolio instability"])},
  {"name":"Gerber","category":"Baby Food","sub_category":"Baby Food","parent_like":"Nestle","acquired_year":2007,"founded_year":1927,"pe_owned":0,"contradiction_score":70,"founder_names":"Daniel Frank Gerber","origin_story":"Daniel Gerber started Gerber Products Company in 1927 after his wife spent hours straining solid food for their baby. It became the dominant baby food brand in America.","headline_finding":"Nestle acquired Gerber in 2007 for $5.5B. Nestle is the same company repeatedly cited by WHO for violating the International Code of Marketing of Breast-milk Substitutes.","marketing_claims":"Good food for babies, its in our DNA","certifications":"","share_text":"Gerber baby food is owned by Nestle, the company repeatedly cited for violating breast-milk marketing codes globally. Check it on Traced.","contradiction_reasons":json.dumps(["Nestle acquisition 2007 for $5.5B","Nestle faces repeated WHO/UNICEF code violations for infant formula marketing","Congressional report 2021 found heavy metals in Gerber products","Nestle faces ongoing water rights controversies globally"])},
  {"name":"Beech-Nut","category":"Baby Food","sub_category":"Baby Food","parent_like":"Morinaga","acquired_year":2013,"founded_year":1891,"pe_owned":0,"contradiction_score":52,"founder_names":"Raymond Lipe","origin_story":"Beech-Nut began as a meat packing company in 1891 before pivoting to baby food in 1931. It has changed ownership multiple times and is now owned by Japanese confectionery company Morinaga.","headline_finding":"Japanese confectionery company Morinaga acquired Beech-Nut in 2013. Beech-Nut pleaded guilty in 2013 to selling adulterated apple juice concentrate.","marketing_claims":"Real food for babies","certifications":"Non-GMO Project Verified","share_text":"Beech-Nut baby food is owned by Japanese candy company Morinaga since 2013. The brand also pleaded guilty to selling adulterated juice. Check it on Traced.","contradiction_reasons":json.dumps(["Morinaga (Japanese confectionery company) ownership","2013 guilty plea for selling adulterated apple juice","Congressional heavy metals report 2021 included Beech-Nut","Parent company is primarily a candy and confectionery manufacturer"])},
  {"name":"Nature Made","category":"Supplements","sub_category":"Vitamins","parent_like":"Pharmavite","acquired_year":None,"founded_year":1971,"pe_owned":0,"contradiction_score":38,"founder_names":"","origin_story":"Pharmavite LLC founded Nature Made in 1971. It became the #1 selling vitamin brand in the US pharmacist-recommended category. Pharmavite itself is owned by Otsuka Holdings of Japan.","headline_finding":"Nature Made is made by Pharmavite, which is owned by Otsuka Holdings, a Japanese pharmaceutical conglomerate. The brand independence is two layers removed.","marketing_claims":"#1 pharmacist recommended vitamin brand","certifications":"USP Verified","share_text":"Nature Made vitamins are made by Pharmavite, which is owned by Japanese pharma giant Otsuka Holdings. Check the ownership chain on Traced.","contradiction_reasons":json.dumps(["Owned by Japanese conglomerate Otsuka Holdings via Pharmavite","USP verification does not guarantee ingredient efficacy","Vitamin supplement industry has weak FDA oversight"])},
  {"name":"Airborne","category":"Supplements","sub_category":"Immune Support","parent_like":"Haleon","acquired_year":2012,"founded_year":1997,"pe_owned":0,"contradiction_score":75,"founder_names":"Victoria Knight-McDowell","origin_story":"Schoolteacher Victoria Knight-McDowell created Airborne in 1997 claiming it boosted immunity. It became a $300M brand before a class action settlement forced it to remove health claims.","headline_finding":"Haleon (formerly GSK Consumer) owns Airborne. The brand paid $23.3M to settle a class action lawsuit that found its immune support claims were unsubstantiated.","marketing_claims":"Immune support formula","certifications":"","share_text":"Airborne paid $23.3M to settle a class action over false immune claims. Now owned by Haleon (spun off from GlaxoSmithKline). Check it on Traced.","contradiction_reasons":json.dumps(["$23.3M FTC/class action settlement over false immune claims","Haleon ownership (spun off from GlaxoSmithKline 2022)","FTC found original treats cold claims unsubstantiated","Reformulated but similar marketing narrative maintained"])},
  {"name":"Emergen-C","category":"Supplements","sub_category":"Immune Support","parent_like":"Haleon","acquired_year":2012,"founded_year":1978,"pe_owned":0,"contradiction_score":60,"founder_names":"Alacer Corp","origin_story":"Alacer Corporation launched Emergen-C in 1978 as a vitamin C supplement in a fizzy powder format. Pfizer acquired it in 2012 and it later moved to Haleon.","headline_finding":"Emergen-C is owned by Haleon, spun off from GlaxoSmithKline. Pfizer had a significant stake during the GSK Consumer Healthcare period.","marketing_claims":"Your daily dose of feel-good","certifications":"","share_text":"Emergen-C is owned by Haleon, a company spun off from GlaxoSmithKline with Pfizer as a major former stakeholder. Check it on Traced.","contradiction_reasons":json.dumps(["Haleon ownership (GSK/Pfizer spinoff)","High-dose vitamin C claims not conclusively proven","Parent GSK has paid billions in pharmaceutical settlement fines","Vitamin C immune benefit marketing is contested by research"])},
  {"name":"Centrum","category":"Supplements","sub_category":"Multivitamins","parent_like":"Haleon","acquired_year":2012,"founded_year":1978,"pe_owned":0,"contradiction_score":42,"founder_names":"","origin_story":"Centrum was developed by Lederle Laboratories in 1978 and became the world's best-selling multivitamin. It passed through American Home Products, Wyeth, and Pfizer before landing at Haleon.","headline_finding":"Centrum is owned by Haleon plc, which was spun off from GlaxoSmithKline in 2022. The world's #1 multivitamin has changed pharma hands four times since 1978.","marketing_claims":"Complete from A to Zinc","certifications":"","share_text":"Centrum multivitamins are owned by Haleon, a pharma spinoff. The world's number one vitamin has changed conglomerate hands four times since 1978. Check it on Traced.","contradiction_reasons":json.dumps(["Four ownership changes since 1978","Haleon spun off from GlaxoSmithKline/Pfizer in 2022","Synthetic vitamin absorption debates","GSK multi-billion dollar pharmaceutical settlement history"])},
  {"name":"Lightlife","category":"Plant-Based","sub_category":"Plant-Based Meat","parent_like":"Maple Leaf","acquired_year":2017,"founded_year":1979,"pe_owned":0,"contradiction_score":55,"founder_names":"Michael Cohen","origin_story":"Lightlife was founded in 1979 as a tempeh company in Massachusetts. It pioneered plant-based deli meats in the 1980s and was acquired by ConAgra, then Maple Leaf Foods.","headline_finding":"Canadian meat conglomerate Maple Leaf Foods acquired Lightlife in 2017. Maple Leaf is one of Canada's largest conventional meat processors.","marketing_claims":"Real. Simple. Plant-based.","certifications":"Non-GMO Project Verified","share_text":"Lightlife plant-based foods is owned by Maple Leaf Foods, one of Canada's largest conventional meat companies. Check the contradiction on Traced.","contradiction_reasons":json.dumps(["Owned by Maple Leaf Foods, a major conventional meat conglomerate","Maple Leaf CFO described plant-based as strategic hedge not core mission","ConAgra previously owned (2000-2017)"])},
  {"name":"Gardein","category":"Plant-Based","sub_category":"Plant-Based Meat","parent_like":"Conagra","acquired_year":2014,"founded_year":2003,"pe_owned":0,"contradiction_score":58,"founder_names":"Yves Potvin","origin_story":"Yves Potvin founded Gardein in 2003, building on his experience at Yves Veggie Cuisine. ConAgra Brands acquired Gardein in 2014.","headline_finding":"ConAgra Brands (Birds Eye, Slim Jim, Reddi Wip) owns Gardein. The plant-based brand is part of a $12B conventional food conglomerate.","marketing_claims":"Deliciously different plant-based protein","certifications":"Non-GMO Project Verified","share_text":"Gardein plant-based is owned by ConAgra Brands, maker of Slim Jim, Swiss Miss, and Vlasic. Check it on Traced.","contradiction_reasons":json.dumps(["ConAgra acquisition 2014","Parent makes Slim Jim, Birds Eye, and dozens of conventional products","ConAgra lobbied against GMO labeling","Plant-based as portfolio hedge for conventional meat seller"])},
  {"name":"Sweet Earth","category":"Plant-Based","sub_category":"Plant-Based Meat","parent_like":"Nestle","acquired_year":2017,"founded_year":2011,"pe_owned":0,"contradiction_score":62,"founder_names":"Brian Swette, Kelly Swette","origin_story":"Brian and Kelly Swette founded Sweet Earth in California in 2011 with a mission around plant-forward eating. Nestle acquired it in 2017 to enter the plant-based category.","headline_finding":"Nestle acquired Sweet Earth in 2017 to launch Awesome Burger and expand into plant-based. Sweet Earth is Nestle's primary plant-based meat brand in the US.","marketing_claims":"Enlightened foods for a better world","certifications":"Non-GMO Project Verified","share_text":"Sweet Earth plant-based is owned by Nestle since 2017. Check the contradiction between the brand mission and its parent company on Traced.","contradiction_reasons":json.dumps(["Nestle acquisition 2017","Nestle CEO publicly stated water is not a human right (retracted)","Nestle water extraction controversies in drought regions","Founders departed post-acquisition"])},
  {"name":"Beyond Meat","category":"Plant-Based","sub_category":"Plant-Based Meat","parent_like":None,"acquired_year":None,"founded_year":2009,"pe_owned":0,"contradiction_score":35,"founder_names":"Ethan Brown","origin_story":"Ethan Brown founded Beyond Meat in 2009 in Los Angeles. The company IPO'd in 2019 with the best-performing first day of trading for a major US company since 2000.","headline_finding":"Beyond Meat is publicly traded (Nasdaq: BYND). The company has faced sales declines and COO arrested for biting a man's nose in 2022.","marketing_claims":"Go beyond, better for you and the planet","certifications":"Non-GMO Project Verified","share_text":"Beyond Meat is publicly traded (Nasdaq: BYND) with significant institutional investor pressure for profitability. Check it on Traced.","contradiction_reasons":json.dumps(["Publicly traded, shareholder profit pressure","COO arrested in 2022 for biting man's nose, resigned","Sales declining since 2021 peak","Highly processed product despite natural claims"])},
  {"name":"Siete Family Foods","category":"Snacks","sub_category":"Grain-Free Snacks","parent_like":"PepsiCo","acquired_year":2024,"founded_year":2014,"pe_owned":0,"contradiction_score":72,"founder_names":"Veronica Garza, Miguel Garza","origin_story":"Veronica Garza created grain-free tortillas while managing an autoimmune condition. The Garza family built Siete into a $500M brand serving the Latinx health-conscious market.","headline_finding":"PepsiCo acquired Siete Family Foods in 2024 for $1.2B. The family values-driven grain-free brand is now owned by PepsiCo (Doritos, Cheetos, Fritos, Lay's).","marketing_claims":"Grain free, made with love, for la familia","certifications":"Non-GMO Project Verified, Paleo Certified","formula_changed_post_acquisition":0,"share_text":"Siete Family Foods was sold to PepsiCo (Doritos, Cheetos) for $1.2B in 2024. Check it on Traced.","contradiction_reasons":json.dumps(["PepsiCo acquisition 2024 for $1.2B","Parent simultaneously sells Doritos, Cheetos, Fritos","PepsiCo lobbied against soda taxes, GMO labeling, and nutrition warning labels","Founding family retained roles, formula change risk remains"])},
  {"name":"Perfect Bar","category":"Snacks","sub_category":"Protein Bars","parent_like":"Mondelez","acquired_year":2019,"founded_year":2005,"pe_owned":0,"contradiction_score":65,"founder_names":"Bud Keith","origin_story":"Bud Keith's father Barney developed the original recipe in the 1950s. Bud and his siblings commercialized it as Perfect Bar in 2005, selling from a van. Mondelez acquired it in 2019.","headline_finding":"Mondelez International (Oreo, Cadbury, Toblerone) acquired Perfect Bar in 2019. The refrigerated protein bar brand is now part of the world's largest snack company.","marketing_claims":"Real food energy, refrigerated for freshness","certifications":"Non-GMO Project Verified, Certified Gluten-Free","share_text":"Perfect Bar is owned by Mondelez International (Oreo, Cadbury, Ritz) since 2019. Check it on Traced.","contradiction_reasons":json.dumps(["Mondelez acquisition 2019","Parent sells Oreo, Cadbury, and highly processed snack products","Mondelez lobbied against sugar taxes","Family-values brand narrative under corporate ownership"])},
  {"name":"GoMacro","category":"Snacks","sub_category":"Protein Bars","parent_like":None,"acquired_year":None,"founded_year":2003,"pe_owned":0,"contradiction_score":12,"founder_names":"Amelia Kirchoff, Janna Kirchoff","origin_story":"Amelia Kirchoff started making macrobiotic bars in her Wisconsin farmhouse in 2003 after a cancer diagnosis led her to adopt a plant-based diet. Her daughter Janna built it into a company.","headline_finding":"GoMacro remains family-owned and independent as of 2025. One of the few certified organic B Corp protein bar companies not acquired by a conglomerate.","marketing_claims":"Organic, plant-based, certified B Corp","certifications":"USDA Organic, Non-GMO Project Verified, Certified B Corp, Certified Vegan","share_text":"GoMacro is still family-owned and a certified B Corp as of 2025. Rare in the protein bar category. Check it on Traced.","contradiction_reasons":json.dumps(["Truly independent, family-owned","Certified B Corp maintained","No PE investment detected"])},
  {"name":"Chomps","category":"Snacks","sub_category":"Meat Snacks","parent_like":None,"acquired_year":None,"founded_year":2012,"pe_owned":0,"contradiction_score":15,"founder_names":"Pete Maldonado, Rashid Ali","origin_story":"Pete Maldonado and Rashid Ali founded Chomps in 2012 to create a cleaner grass-fed meat stick. The brand bootstrapped to $100M+ revenue without outside investment.","headline_finding":"Chomps remains independently owned as of 2025. The founders bootstrapped to significant scale without PE or corporate acquisition.","marketing_claims":"No BS beef sticks, grass-fed and grass-finished","certifications":"Non-GMO Project Verified, Whole30 Approved, Paleo Certified, Certified Gluten-Free","share_text":"Chomps beef sticks remain independently owned as of 2025, bootstrapped to over $100M revenue without selling out. Check it on Traced.","contradiction_reasons":json.dumps(["Independently owned","Grass-fed sourcing claims independently verified","No PE or conglomerate acquisition"])},
  {"name":"AG1","category":"Supplements","sub_category":"Greens Powder","parent_like":None,"acquired_year":None,"founded_year":2010,"pe_owned":1,"pe_firm":"Strand Equity","contradiction_score":55,"founder_names":"Chris Ashenden","origin_story":"Chris Ashenden launched Athletic Greens in New Zealand in 2010. The company rebranded to AG1 in 2022 and became known for aggressive influencer marketing and podcast sponsorships.","headline_finding":"AG1 is PE-backed by Strand Equity Partners, which invested $115M in 2022 at a $1.2B valuation. The brand spends an estimated $200M+/year on influencer marketing.","marketing_claims":"Comprehensive daily nutrition in one scoop","certifications":"NSF Certified for Sport, Informed Sport, Non-GMO Project Verified","share_text":"AG1 is PE-backed at a $1.2B valuation and reportedly spends $200M/year on influencer marketing for a $79/month product. Check it on Traced.","contradiction_reasons":json.dumps(["PE-backed by Strand Equity at $1.2B valuation","Estimated $200M+ annual influencer/podcast marketing spend","75 ingredients, scientific efficacy of combination not independently validated","Subscription model makes cancellation difficult by design"])},
  {"name":"Purely Elizabeth","category":"Breakfast","sub_category":"Granola & Oats","parent_like":None,"acquired_year":None,"founded_year":2009,"pe_owned":0,"contradiction_score":20,"founder_names":"Elizabeth Stein","origin_story":"Elizabeth Stein started Purely Elizabeth in 2009 making granola from her New York apartment. The brand grew to wide retail distribution while maintaining clean ingredients.","headline_finding":"Remains independently owned as of 2025. No major acquisition or PE investment detected.","marketing_claims":"Ancient grain granola, clean ingredients","certifications":"Non-GMO Project Verified, Certified Gluten-Free","share_text":"Purely Elizabeth granola is still independently owned by founder Elizabeth Stein as of 2025. Check it on Traced.","contradiction_reasons":json.dumps(["Independent founder-owned brand","No major acquisition","Clean ingredient integrity maintained"])},
  {"name":"LMNT","category":"Beverages","sub_category":"Electrolytes","parent_like":None,"acquired_year":None,"founded_year":2018,"pe_owned":0,"contradiction_score":22,"founder_names":"Robb Wolf, Tyler Cartwright","origin_story":"Robb Wolf (Paleo Solution author) and Tyler Cartwright created LMNT in 2018 as a high-sodium, no-sugar electrolyte drink for the keto/carnivore community.","headline_finding":"LMNT remains independently owned as of 2025. The company is bootstrapped and direct-to-consumer focused.","marketing_claims":"Science-backed electrolytes, no sugar no BS","certifications":"Non-GMO Project Verified, Paleo Certified, Keto Certified","share_text":"LMNT electrolytes are still independently owned and bootstrapped as of 2025. Check it on Traced.","contradiction_reasons":json.dumps(["Independently owned bootstrapped company","High sodium content (1000mg), controversial for some health conditions","No PE or corporate acquisition"])},
  {"name":"Nuun","category":"Beverages","sub_category":"Electrolytes","parent_like":"Nestle","acquired_year":2021,"founded_year":2004,"pe_owned":0,"contradiction_score":55,"founder_names":"Tim Cote","origin_story":"Tim Cote founded Nuun in Seattle in 2004 as an electrolyte tablet for endurance athletes. The brand grew through running and triathlon communities before being acquired.","headline_finding":"Nestle Health Science acquired Nuun in 2021. The clean athlete electrolyte brand is now part of Nestle's health science portfolio.","marketing_claims":"Clean hydration for active people","certifications":"NSF Certified for Sport, Non-GMO Project Verified","share_text":"Nuun electrolytes were acquired by Nestle Health Science in 2021. The athlete-focused hydration brand is now part of the world's largest food company. Check it on Traced.","contradiction_reasons":json.dumps(["Nestle Health Science acquisition 2021","Nestle water extraction and environmental controversies","Nestle WHO infant formula code violations","Clean athlete branding under global conglomerate"])},
  {"name":"Tofurky","category":"Plant-Based","sub_category":"Plant-Based Meat","parent_like":None,"acquired_year":None,"founded_year":1980,"pe_owned":0,"contradiction_score":14,"founder_names":"Seth Tibbott","origin_story":"Seth Tibbott founded Turtle Island Foods (Tofurky parent) in 1980 in his Oregon farmhouse making tempeh. Tofurky became America's most recognized plant-based holiday roast.","headline_finding":"Tofurky remains independently owned by the Tibbott family as of 2025. One of the longest-running independent plant-based food companies in the US.","marketing_claims":"Plant-based since 1980","certifications":"USDA Organic, Non-GMO Project Verified, Certified Vegan","share_text":"Tofurky has been independently family-owned since 1980, one of the last major plant-based brands not acquired by a meat company. Check it on Traced.","contradiction_reasons":json.dumps(["Truly independent family-owned brand since 1980","No corporate acquisition","Certified organic and vegan"])},
  {"name":"Bare Snacks","category":"Snacks","sub_category":"Baked Snacks","parent_like":"PepsiCo","acquired_year":2018,"founded_year":2001,"pe_owned":0,"contradiction_score":48,"founder_names":"Holly Heber","origin_story":"Holly Heber started Bare Snacks in 2001 making baked apple chips with minimal ingredients. The brand expanded to coconut and banana chips before being acquired.","headline_finding":"PepsiCo's Frito-Lay division acquired Bare Snacks in 2018. The simple-ingredient baked chip brand is now part of the world's largest snack company.","marketing_claims":"Simply baked, nothing to hide","certifications":"Non-GMO Project Verified","share_text":"Bare Snacks (baked apple chips) are owned by PepsiCo's Frito-Lay since 2018. Check it on Traced.","contradiction_reasons":json.dumps(["PepsiCo/Frito-Lay acquisition 2018","Parent makes Doritos, Cheetos, Fritos","Simple ingredient positioning under world's largest snack company","PepsiCo lobbied against nutrition labeling reforms"])},
  {"name":"That's It","category":"Snacks","sub_category":"Fruit Bars","parent_like":None,"acquired_year":None,"founded_year":2012,"pe_owned":0,"contradiction_score":18,"founder_names":"Lior Lewensztain","origin_story":"Lior Lewensztain founded That's It in 2012 with a simple concept: two-ingredient fruit bars with nothing else. The brand expanded to mushroom bites and mini fruit bars.","headline_finding":"That's It remains independently owned as of 2025. No acquisition or PE investment detected.","marketing_claims":"2 ingredients. That's it.","certifications":"USDA Organic, Non-GMO Project Verified, Certified Vegan, Certified Kosher","share_text":"That's It fruit bars are still independently owned as of 2025. Two ingredients, no corporate ownership. Check it on Traced.","contradiction_reasons":json.dumps(["Independently owned","Simple ingredient integrity maintained","No acquisition"])},
  {"name":"One A Day","category":"Supplements","sub_category":"Multivitamins","parent_like":"Bayer","acquired_year":1994,"founded_year":1940,"pe_owned":0,"contradiction_score":50,"founder_names":"","origin_story":"One-A-Day vitamins were launched in 1940. Miles Laboratories developed them. Bayer AG acquired Miles Laboratories in 1978 and has owned One A Day since.","headline_finding":"One A Day is owned by Bayer AG, the German pharmaceutical giant that also makes Roundup (glyphosate herbicide) through its Monsanto acquisition.","marketing_claims":"Complete multivitamin, just one a day","certifications":"","share_text":"One A Day vitamins are owned by Bayer, the company that also owns Roundup/Monsanto. Check it on Traced.","contradiction_reasons":json.dumps(["Bayer AG ownership (pharmaceutical/pesticide conglomerate)","Bayer's Monsanto subsidiary makes Roundup (glyphosate)","Bayer paid $10B+ to settle Roundup cancer lawsuits","Wellness vitamin marketed by herbicide manufacturer"])},
]

inserted = 0
skipped = 0
for b in brands:
    nm = b['name']
    existing = c.execute("SELECT id FROM brands WHERE lower(name)=lower(?)", (nm,)).fetchone()
    if existing:
        skipped += 1
        print(f"  SKIP existing: {nm}")
        continue
    bid = str(uuid.uuid4())
    sl = make_slug(nm)
    parent_id = None
    if b.get('parent_like'):
        parent_id = get_company_id(b['parent_like'])
    c.execute("""INSERT INTO brands (
        id, name, slug, category, sub_category, parent_company_id,
        acquired_year, founded_year, pe_owned, pe_firm,
        contradiction_score, founder_names, origin_story,
        headline_finding, marketing_claims, certifications,
        formula_changed_post_acquisition, formula_change_notes,
        share_text, contradiction_reasons
    ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""", (
        bid, nm, sl,
        b.get('category',''), b.get('sub_category',''), parent_id,
        b.get('acquired_year'), b.get('founded_year'),
        b.get('pe_owned', 0), b.get('pe_firm'),
        b.get('contradiction_score', 0),
        b.get('founder_names',''), b.get('origin_story',''),
        b.get('headline_finding',''), b.get('marketing_claims',''),
        b.get('certifications',''),
        b.get('formula_changed_post_acquisition', 0),
        b.get('formula_change_notes',''),
        b.get('share_text',''),
        b.get('contradiction_reasons','[]'),
    ))
    inserted += 1
    print(f"  Inserted: {nm}")

conn.commit()
print(f"\nPhase 3 COMPLETE: {inserted} inserted, {skipped} skipped")
print("Total brands:", c.execute("SELECT COUNT(*) FROM brands").fetchone()[0])
conn.close()
